# Generated by Django 4.2.16 on 2024-11-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerorvideo',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='temp_banners/'),
        ),
        migrations.AlterField(
            model_name='bannerorvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='temp_videos/'),
        ),
    ]
