# Generated by Django 4.2.16 on 2024-11-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_alter_bannerorvideo_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerorvideo',
            name='file_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
