# Generated by Django 4.2.16 on 2024-11-15 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='card_category',
            new_name='cardCategory',
        ),
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='txn_id',
            new_name='txnid',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='mihpayid',
        ),
    ]
