# Generated by Django 4.2.16 on 2024-11-15 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_card_category_paymentdetails_cardcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='product_info',
            new_name='productinfo',
        ),
    ]
