# Generated by Django 4.2.16 on 2024-11-16 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_register_cover_image_register_points_and_more'),
        ('dashboard', '0002_alter_competition_rules_alter_tournament_rules'),
        ('payments', '0003_rename_product_info_paymentdetails_productinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.competition'),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.tournament'),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.register'),
            preserve_default=False,
        ),
    ]
