# Generated by Django 4.2.16 on 2024-11-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_competition_rules_alter_tournament_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='file_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='file_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
