# Generated by Django 4.2.16 on 2024-11-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_participant_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='file_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='competition_participants_videos/'),
        ),
    ]
