# Generated by Django 4.2.16 on 2024-11-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_participant_file_uri_alter_participant_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
    ]
