# Generated by Django 4.2.16 on 2024-11-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_participant_competition_and_more'),
        ('video', '0004_participant_delete_post_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
