# Generated by Django 4.2.16 on 2024-12-01 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_alter_stage_border_design'),
        ('dashboard', '0007_delete_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels.stage'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels.stage'),
        ),
    ]
