# Generated by Django 4.2.16 on 2024-12-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_competition_is_online_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='tournament',
        ),
    ]
