# Generated by Django 4.2.16 on 2024-12-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_competition_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='registration_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='registration_open_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
