# Generated by Django 4.2.16 on 2024-12-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_competition_registration_close_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='total_rounds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
