# Generated by Django 4.2.16 on 2025-01-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_tournament_total_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='registration_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_open_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
