# Generated by Django 4.2.16 on 2024-11-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_awards_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awards',
            old_name='points_required',
            new_name='votes_required',
        ),
    ]
