# Generated by Django 4.2.16 on 2024-11-30 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_participant_competition_and_more'),
        ('accounts', '0006_alter_register_custom_id_alter_register_dob_and_more'),
        ('video', '0003_alter_comment_post_alter_favorite_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='competition_participants_videos/')),
                ('is_qualified_for_next_round', models.BooleanField(default=False)),
                ('file_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='dashboard.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.register')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='video.participant'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='video.participant'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='video.participant'),
        ),
        migrations.AlterField(
            model_name='share',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='video.participant'),
        ),
    ]
