# Generated by Django 4.2.16 on 2024-12-09 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_winnings'),
        ('video', '0004_participant_delete_post_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='dashboard.tournament'),
            preserve_default=False,
        ),
    ]
