# Generated by Django 4.2.16 on 2024-12-09 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_winnings'),
        ('video', '0005_participant_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='dashboard.competition'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='dashboard.tournament'),
        ),
    ]
