# Generated by Django 4.2.16 on 2025-01-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_alter_participant_competition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='temp_video',
            field=models.FileField(blank=True, null=True, upload_to='competition_participants_temp_videos/'),
        ),
    ]
