# Generated by Django 4.2.16 on 2025-01-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_participant_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='is_qualified_for_next_round',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='tournament',
        ),
    ]
