# Generated by Django 4.2.16 on 2024-12-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='border_design',
            field=models.URLField(blank=True, null=True),
        ),
    ]
